# -*- coding: utf-8 -*-
"""water_purifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aNBahvpc4Gv9-dgSAvJ1BptJImjKBUNZ
"""

pip install bs4

pip install requests

import requests

from bs4 import BeautifulSoup

url="https://www.mysmartprice.com/appliance/pricelist/water-purifiers-price-list-in-india.html"

res=requests.get(url)

res

wat=BeautifulSoup(res.text)

wat

water=wat.select('.prdct-item__name')

water

water_name=[]

for item in water:
  water_name.append(item.text)
  link="www.mysmartprice.com"+item["href"]

water_name

price=wat.select(".prdct-item__prc-val")

price

water_price=[]

for item in price:
  water_price.append(item.text)

water_price

capacity=wat.select(".prdct-item__spcftn-wrpr")

capacity

water_capacity=[]
for item in capacity:
  water_capacity.append(item.text)

water_capacity

import pandas as wt

smart=wt.DataFrame(water_name,columns=['Purifier Name'])

smart

smart['Purifier Rate']=water_price

smart

smart['Capacity']=water_capacity

smart

